### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Butonix** [thetruefuss/elmer#1]
return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: subjects_subject

**Comment by Butonix** [comment]
LINE 1: ...ect"."created", "subjects_subject"."updated" FROM "subjects_...

**Comment by thetruefuss** [comment]
Oops, this is a "chicken and the egg" problem. That's an OperationalError which could be resolved by using try/except block in the codebase where it queries subjects in the database.
